// SuperAdmin User Routes
export const SUPER_ADMIN_USER_PREFIX = '/users';
export const SUPER_ADMIN_USER_ROUTE = SUPER_ADMIN_USER_PREFIX;

export const SUPER_ADMIN_USER_GET_ALL_PREFIX = '/';
export const SUPER_ADMIN_USER_GET_ALL_PATH = SUPER_ADMIN_USER_GET_ALL_PREFIX;

export const SUPER_ADMIN_USER_CREATE_PREFIX = '/create';
export const SUPER_ADMIN_USER_CREATE_PATH = SUPER_ADMIN_USER_CREATE_PREFIX;

export const SUPER_ADMIN_USER_DELETE_PREFIX = '/:id';
export const SUPER_ADMIN_USER_DELETE_PATH = SUPER_ADMIN_USER_DELETE_PREFIX;

// Swagger Tag
export const SUPER_ADMIN_USER_TAG = 'SuperAdmin User';
